name: app
on:
- push
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - run: scripts/install_awscli.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: scripts/app_prepare_env.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET: ${{ secrets.BUCKET }}
    - uses: werf/actions/install@v1.2
    - run: |
        cd $GITHUB_WORKSPACE/app
        source "$(werf ci-env github --as-file)"
        werf converge --disable-auto-host-cleanup=true
      env:
        WERF_ENV: dev
#        werf converge --disable-auto-host-cleanup=true --namespace=$NAMESPACE  # We don't build image here
