name: app
on:
- push
jobs:
  redis-cart:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      with:
        filters: |
          workflow:
          - '.github/workflows/app.yaml'
          src:
          - 'app/redis-cart/**'
    - run: scripts/install_awscli.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: scripts/app_prepare_env.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET: ${{ secrets.BUCKET }}
    - uses: werf/actions/install@v1.2
    - run: |
        cd app/redis-cart
        source "$(werf ci-env github --as-file)"
        werf converge --disable-auto-host-cleanup=true --namespace=$NAMESPACE
